### ISSUE TITLE
Winning Text is not showing.

### ISSUE THREAD

**Issue by hutsori** [awsmug/torro-forms-wheel-of-fortune#1]
Winning text is not showing after you spin.

**Comment by hutsori** [comment]
Fixed it. Not really sure how to use github but yeah.. I think I forked it somehow.

**Comment by mahype** [comment]
What do you have made?

**Comment by hutsori** [comment]
wheel-of-fortune.php  @ 27 changed 

this
`   $data['winning_text'] = $this->settings['winning_text']`
into 
`   $data['winning_text'] = $element->settings['winning_text']->value;`

**Comment by mahype** [comment]
You are totally right! :) Do you have used git repositories or should I add your changes to the code?

**Comment by hutsori** [comment]
Hi Sven,


Please do so. I am not really familiar with the GitHub.

I think it's better for you to update [😊]


Thank you.



________________________________
보낸 사람: Sven Wagener <notifications@github.com>
보낸 날짜: 2016년 7월 13일 수요일 오전 8:26
받는 사람: awsmug/torro-forms-wheel-of-fortune
참조: hutsori; State change
제목: Re: [awsmug/torro-forms-wheel-of-fortune] Winning Text is not showing. (#1)


You are totally right! :) Do you have used git repositories or should I add your changes to the code?
